apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  gitops.weave.works/app-id: 7c5e0c46-c21d-4b62-901e-fac09dc9bb1a
kind: Kustomization
metadata:
  name: test-4
  namespace: test-space
resources:
- ./app.yaml
