---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-67c1f3f10fa8dae4b6352bcf5fe954cd
  name: microservices-demo
  namespace: wego-system
spec:
  branch: staging
  config_url: ssh://git@github.com/JamWils/gitops-repo-000.git
  deployment_type: helm
  helm_target_namespace: sock-shop
  path: ./deploy/kubernetes/helm-chart
  source_type: git
  url: ssh://git@github.com/JamWils/microservices-demo.git
