---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wego-app
  namespace: flux-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wego-app
        test: this
    spec:
      serviceAccountName: wego-app-service-account
      containers:
        - name: wego-app
          image: jamweave/weave-gitops-test:011820244 # {"$imagepolicy": "wego-system:gitops-app"}
          args: [ "ui", "run", "-l", "--helm-repo-namespace", "flux-system" ]
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: IfNotPresent
  selector:
    matchLabels:
      app: wego-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-resources
  namespace: flux-system
subjects:
  - kind: ServiceAccount
    name: wego-app-service-account
    namespace: flux-system
roleRef:
  kind: Role
  name: resources-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resources-reader
  namespace: flux-system
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get","create" ]
  - apiGroups: [ "kustomize.toolkit.fluxcd.io" ]
    resources: [ "kustomizations" ]
    verbs: [ "get" ]
  - apiGroups: [ "helm.toolkit.fluxcd.io" ]
    resources: [ "helmreleases" ]
    verbs: [ "get" ]
  - apiGroups: [ "source.toolkit.fluxcd.io" ]
    resources: [ "helmrepositories" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "source.toolkit.fluxcd.io" ]
    resources: [ "gitrepositories" ]
    verbs: [ "get","list" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wego-app-service-account
  namespace: flux-system
secrets:
  - name: wego-app-service-account-token
---
apiVersion: v1
kind: Service
metadata:
  name: wego-app
  namespace: flux-system
spec:
  selector:
    app: wego-app
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
