apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/weave-gitops
      sourceRef:
        kind: GitRepository
        name: ww-gitops
  values:
    namespace: flux-system
    image: rc1
    containerRegistry: sympatheticmoose/weave-gitops
    adminPassword: JDJiJDEyJEU5STRSU01VWTVMYUJrVHNQLmxiTy4zTDB2M1BTUHZIb1htN29kSE80TXN4MXZiZmVwRzdX
  interval: 1m0s