apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  releaseName: gitops-server
  targetNamespace: flux-system
  chart:
    spec:
      chart: ./charts/gitops-server
      sourceRef:
        kind: GitRepository
        name: ww-gitops
  install:
    remediation:
      retries: 3
  values:
    namespace: flux-system
    additionalArgs: ["--insecure"]
    image:
      tag: v0.7.0-rc5
      repository: ghcr.io/weaveworks/wego-app
    adminUser:
      create: true
      username: d2Vnby1hZG1pbi00MjQy
      password: JDJhJDEyJE9wQjBjWGk1RWNwZVRnUmZ4Z0NOTE9ENU1NOEVhL1BwVkloYXZpTjFQVldBc0p3a2lXRE5x
  interval: 1m0s