---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-09a3dbcc39ce3b00cc3ebf41045034ca
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/JamWils/gitops-repo-000.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/JamWils/gitops-repo-000.git
