apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  gitops.weave.works/app-id: 2d612ac8-01c5-4bd2-bd31-201a273981f3
kind: Kustomization
metadata:
  name: app-15
  namespace: wego-system
resources:
- ./app.yaml
