apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  gitops.weave.works/app-id: c478516a-697b-4d4a-9946-68c65dd6aa29
kind: Kustomization
metadata:
  name: app-21
  namespace: wego-system
resources:
- ./app.yaml
- .weave-gitops/apps/app-21/kust-2-wego-system-kustomization.yaml
- .weave-gitops/apps/app-21/kust-3-wego-system-kustomization.yaml
- .weave-gitops/apps/app-21/kust-6-wego-system-kustomization.yaml
